#---- Conda config files and environments ----
"conda":
    "common":
        "yaml": "workflow/envs/conda.common.yaml"
        "name": "base"
    "gatk3":
        "yaml": "workflow/envs/conda.gatk3.yaml"
        "name": "gatk3"

#----
#---- Directory structure config ----

#---- Input ----
"input_dir": "input/"

#----

#----
#---- Output directory and subdirectories ----
"out_dir": "results"
#--------- Subdirectories --------
"out_subdir_list":
  - "extracted_fastq"
  - "extracted_bam"
  - "intermediate_bam"
  - "realigned_bam"
  - "str"
  - "log"
  - "benchmark"
  - "config"
  - "cluster_log"
  - "cluster_error"

#--------

#---- Tool parameters ----
"parameters":
    "default":
        "threads":
            "extract_alignments":             1
            "add_flanks":                     1
            "extract_properly_mapped_reads":  4
            "bwa_map":                        4
            "samtools_sort":                  2
            "samtools_fixmate":               1
            "realign_bam":                    4
            "hipSTR":                         1
            "filter_hipSTR":                  1
            "samtools_markdup":               1
            "convert_hipSTR_vcf":             1
            "structure":                      1
            "generate_config_for_structure":  1
            "extract_q_table":                1
            "prepare_clumpp_input":           1
            "generate_config_for_clumpp":     1
            "clumpp":                         1
            "generate_pong_script":           2
            "create_files_for_pong":          1

        "memory_mb":
            "extract_alignments":               1000
            "add_flanks":                       100
            "extract_properly_mapped_reads":    3000
            "bwa_map":                          10000
            "samtools_per_thread":              500
            "realign_bam":                      3000
            "hipSTR":                           3000
            "filter_hipSTR":                    3000
            "convert_hipSTR_vcf":               3000
            "structure":                        3000
            "generate_config_for_structure":    100
            "extract_q_table":                  100
            "prepare_clumpp_input":             100
            "generate_config_for_clumpp":       100
            "clumpp":                           3000
            "generate_pong_script":             3000
            "create_files_for_pong":            100

        "time": #qTODO: adjust
            "extract_alignments":               "00:05:00"
            "add_flanks":                       "00:05:00"
            "extract_properly_mapped_reads":    "01:00:00"
            "bwa_map":                          "04:00:00"
            "realign_bam":                      "04:00:00"
            "hipSTR":                           "02:00:00"
            "filter_hipSTR":                    "02:00:00"
            "convert_hipSTR_vcf":               "01:00:00"
            "structure":                        "12:00:00"
            "generate_config_for_structure":    "00:05:00"
            "extract_q_table":                  "00:10:00"
            "prepare_clumpp_input":             "00:05:00"
            "generate_config_for_clumpp":       "00:05:00"
            "clumpp":                           "02:00:00"
            "generate_pong_script":             "02:00:00"
            "create_files_for_pong":            "00:05:00"

        "tool_options":
            "hipSTR":
                "min_reads":                5
                "min_call_qual":            0.9
                "max_call_flank_indel":     0.15
                "max_call_stutter":         0.15
                "min_call_allele_bias":     -2
                "min_call_strand_bias":     -2
            "convert_hipSTR_vcf":
                "amplicon_id_column_name":  "primer_pair"
                "amplicon_len_column_name": "amplicon_len"
            "structure":
                "extraparams_file": "config/tools/structure/extraparams"
                "number_of_runs": 3
                "K_list":
                    - 2
                    - 3
                    - 4
                    - 5
                    - 6
                "config_file_parameters":
                    "BURNIN":                    1000
                    "NUMREPS":                   10000
                    "LABEL":                     1
                    "POPDATA":                   1
                    "POPFLAG":                   0
                    "LOCDATA":                   0
                    "PHENOTYPE":                 0
                    "MARKERNAMES":               1
                    "MAPDISTANCES":              0
                    "ONEROWPERIND":              0
                    "PHASEINFO":                 0
                    "PHASED":                    0
                    "RECESSIVEALLELES":          0
                    "EXTRACOLS":                 0
                    "NOADMIX":                   0
                    "LINKAGE":                   0
                    "USEPOPINFO":                0
                    "LOCPRIOR":                  0
                    "INFERALPHA":                1
                    "ALPHA":                     1.0
                    "POPALPHAS":                 0
                    "UNIFPRIORALPHA":            1
                    "ALPHAMAX":                  10.0
                    "ALPHAPROPSD":               0.025
                    "FREQSCORR":                 1
                    "ONEFST":                    0
                    "FPRIORMEAN":                0.01
                    "FPRIORSD":                  0.05
                    "INFERLAMBDA":               0
                    "LAMBDA":                    1.0
                    "COMPUTEPROB":               1
                    "PFROMPOPFLAGONLY":          0
                    "ANCESTDIST":                0
                    "STARTATPOPINFO":            0
                    "METROFREQ":                 10
                    "UPDATEFREQ":                1
                "extra_config_file_parameters": []
            "clumpp":
                "config_file_parameters":
                    "DATATYPE":                  0
                        # The type of data to be read in.
                        # 0 = individual data in the file
                        # specified by INDFILE, 1 = population
                        # data in the file specified by
                        # POPFILE.
                    "M":                         1
                        # Method to be used (1 = FullSearch,
                        # 2 = Greedy, 3 = LargeKGreedy).
                    "W":                         0
                        # Weight by the number of individuals
                        # in each population as specified in
                        # the datafile (1 if yes, 0 if no).
                    "S":                         2
                        # Pairwise matrix similarity statistic
                        # to be used. 1 = G, 2 = G'.
                    # - Additional options for the Greedy and LargeKGreedy algorithm (M = 2 or 3) -
                    "GREEDY_OPTION":             2
                        # 1 = All possible input orders,
                        # 2 = random input orders,
                        # 3 = pre-specified input orders.
                    "REPEATS":                   100
                        # If GREEDY_OPTION = 2, then REPEATS
                        # determines the number of random input
                        # orders to be tested. If GREEDY_OPTION
                        # = 3, then REPEATS is the number of
                        # input orders in PERMUTATIONFILE.
                     # --------------- Optional outputs --------------------------------------------
                    "PRINT_PERMUTED_DATA":       2
                        # Print the permuted data (clusters) in
                        # INDFILE or POPFILE to
                        # PERMUTED_DATAFILE (0 = don't print,
                        # 1 = print into one file, 2 = print
                        # into separate files for each run).
                    "PRINT_EVERY_PERM":          0
                        # Print every tested permutation of the
                        # runs and the corresponding value of
                        # H to a file specified by
                        # EVERY_PERMFILE (0 = don't print,
                        # 1 = print).
                        # Note that printing may result in a
                        # very large file.
                    "PRINT_RANDOM_INPUTORDER":      0
                        # Print random input orders of runs to
                        # RANDOM_INPUTORDER (0 = don't print,
                        # 1 = print). This option is only
                        # available if GREEDY_OPTION = 2.
                    # --------------- Advanced options --------------------------------------------
                    "OVERRIDE_WARNINGS":             0
                        # This option allows the user to
                        # override non-crucial warnings from
                        # the program (0 allow warnings, 1 do
                        # not issue non-crucial warnings).
                    "ORDER_BY_RUN":                 1                # Permute the clusters of the output

"stage_coretools":
    "alignment":            "bwa"
    "indel_realignment":    "gatk3"
    "str_calling":          "hipSTR"
    "admixture":            "structure"

"coretool_option_sets": []

"ploidy": 2

"bam_suffix":       ""                  # ".mzib.hic.purged.mkdup"
"str_loci_bed":     "str_loci.bed"      # Bed file with coordinates of str loci including primers
"flank_len":        1000                # length of flank to use for first step of alignment extraction
"str_repeat_bed":   "str_repeat.bed"    # Bed file with coordinates and monomer info of the repeats within  str loci
"str_loci_len_file": null
"pop_file": null # two column tab-separated file. First column should contain sample ids, second - population ids

"absent_allel_alias": "-100"


"reference": "reference.fasta" # bwa index files MUST have same prefix as full filename of the reference
# Bam file names MUST follow this pattern: <sample_id><bam_suffix>.bam, where <s>
# input/
#      <sample_id>/
#                 <sample_id><bam_suffix>.bam
#                 <sample_id><bam_suffix>.bam.bai

#---- Pipeline modes ----

#"mode": "assembly"                # Allowed: "preprocessing", "qc", "assembly"
#"preprocessing_mode": "default"   # Allowed: "default"
#"qc_mode": "default"              # Allowed: "default"
#"assembly_mode": "full"           # Allowed: "default", "full", "purge_dups", "contig"; custom modes could be set in config file


"parameter_set": "default" # Choice of genome-size based set of parameters
"use_existing_envs": True # works only if --use-conda flag was set in snakemake command

