#---- Conda config files and environments ----
"conda":
    "common":
        "yaml": "workflow/envs/conda.common.yaml"
        "name": "base"
    "gatk3":
        "yaml": "workflow/envs/conda.gatk3.yaml"
        "name": "gatk3"

#----
#---- Directory structure config ----

#---- Input ----
"input_dir": "input/"

#----

#----
#---- Output directory and subdirectories ----
"out_dir": "results"
#--------- Subdirectories --------
"out_subdir_list":
  - "extracted_fastq"
  - "extracted_bam"
  - "intermediate_bam"
  - "realigned_bam"
  - "str"
  - "log"
  - "benchmark"
  - "config"
  - "cluster_log"
  - "cluster_error"

#--------

#---- Tool parameters ----
"parameters":
    "default":
        "threads":
            "extract_alignments":             1
            "add_flanks":                     1
            "extract_properly_mapped_reads":  4
            "bwa_map":                        4
            "samtools_sort":                  2
            "samtools_fixmate":               1
            "realign_bam":                    4
            "hipSTR":                         1
            "filter_hipSTR":                  1
            "samtools_markdup":               1
            "convert_hipSTR_vcf":             1
            "structure":                      1
            "generate_config_for_structure":  1

        "memory_mb":
            "extract_alignments":               1000
            "add_flanks":                       100
            "extract_properly_mapped_reads":    3000
            "bwa_map":                          10000
            "samtools_per_thread":              500
            "realign_bam":                      3000
            "hipSTR":                           3000
            "filter_hipSTR":                    3000
            "convert_hipSTR_vcf":               3000
            "structure":                        3000
            "generate_config_for_structure":    100

        "time": #TODO: adjust
            "extract_alignments":               "00:05:00"
            "add_flanks":                       "00:05:00"
            "extract_properly_mapped_reads":    "01:00:00"
            "bwa_map":                          "04:00:00"
            "realign_bam":                      "04:00:00"
            "hipSTR":                           "02:00:00"
            "filter_hipSTR":                    "02:00:00"
            "convert_hipSTR_vcf":               "01:00:00"
            "structure":                        "04:00:00"
            "generate_config_for_structure":    "00:05:00"

        "tool_options":
            "hipSTR":
                "min_reads":                5
                "min_call_qual":            0.9
                "max_call_flank_indel":     0.15
                "max_call_stutter":         0.15
                "min_call_allele_bias":     -2
                "min_call_strand_bias":     -2
            "convert_hipSTR_vcf":
                "amplicon_id_column_name":  "primer_pair"
                "amplicon_len_column_name": "amplicon_len"
            "structure":
                "extraparams_file": "config/tools/structure/extraparams"
                "K_list":
                    - 2
                    - 3
                    - 4
                    - 5
                    - 6
                "config_file_parameters":
                    "BURNIN":                    10000
                    "NUMREPS":                   100000
                    "LABEL":                     1
                    "POPDATA":                   0
                    "POPFLAG":                   0
                    "LOCDATA":                   0
                    "PHENOTYPE":                 0
                    "MARKERNAMES":               1
                    "MAPDISTANCES":              0
                    "ONEROWPERIND":              0
                    "PHASEINFO":                 0
                    "PHASED":                    0
                    "RECESSIVEALLELES":          0
                    "EXTRACOLS":                 0
                    "NOADMIX":                   0
                    "LINKAGE":                   0
                    "USEPOPINFO":                0
                    "LOCPRIOR":                  0
                    "INFERALPHA":                1
                    "ALPHA":                     1.0
                    "POPALPHAS":                 0
                    "UNIFPRIORALPHA":            1
                    "ALPHAMAX":                  10.0
                    "ALPHAPROPSD":               0.025
                    "FREQSCORR":                 1
                    "ONEFST":                    0
                    "FPRIORMEAN":                0.01
                    "FPRIORSD":                  0.05
                    "INFERLAMBDA":               0
                    "LAMBDA":                    1.0
                    "COMPUTEPROB":               1
                    "PFROMPOPFLAGONLY":          0
                    "ANCESTDIST":                0
                    "STARTATPOPINFO":            0
                    "METROFREQ":                 10
                    "UPDATEFREQ":                1
                "extra_config_file_parameters": []

"stage_coretools":
    "alignment":            "bwa"
    "indel_realignment":    "gatk3"
    "str_calling":          "hipSTR"
    "admixture":            "structure"

"coretool_option_sets": []

"ploidy": 2

"bam_suffix":       ""                  # ".mzib.hic.purged.mkdup"
"str_loci_bed":     "str_loci.bed"      # Bed file with coordinates of str loci including primers
"flank_len":        1000                # length of flank to use for first step of alignment extraction
"str_repeat_bed":   "str_repeat.bed"    # Bed file with coordinates and monomer info of the repeats within  str loci
"str_loci_len_file": null

"absent_allel_alias": "-100"


"reference": "reference.fasta" # bwa index files MUST have same prefix as full filename of the reference
# Bam file names MUST follow this pattern: <sample_id><bam_suffix>.bam, where <s>
# input/
#      <sample_id>/
#                 <sample_id><bam_suffix>.bam
#                 <sample_id><bam_suffix>.bam.bai

#---- Pipeline modes ----

#"mode": "assembly"                # Allowed: "preprocessing", "qc", "assembly"
#"preprocessing_mode": "default"   # Allowed: "default"
#"qc_mode": "default"              # Allowed: "default"
#"assembly_mode": "full"           # Allowed: "default", "full", "purge_dups", "contig"; custom modes could be set in config file


"parameter_set": "default" # Choice of genome-size based set of parameters
"use_existing_envs": True # works only if --use-conda flag was set in snakemake command

