#---- Bioconda config ----
"name": "common"
"channels":
  - "mahajrod"
  - "conda-forge"
  - "bioconda"
  - "ipyrad"
"dependencies":
  - "routoolpa"
  - "mavr"
  - "mace"
  - "pyvcf"
  - "samtools"
  - "bwa"
  - "bazam"
  - "clumpp"
  - "structure"
